### ISSUE TITLE
Warning: Undefined array key 4 in /home/...../lib/plugins/iframeinterwiki/syntax.php on line 55

### ISSUE THREAD

**Issue by DavWai** [roquess/dokuwiki-plugin-iframeinterwiki#2]
Problem with the plugin

Call code = {{url>https://..../files_candidats.php ,800px}}

Frame with 800 px height...
This is a warning.... Parameters problem ?

**Comment by roquess** [comment]
Hello, I pushed a correction for this warning. On the other hand, the syntax is without commas. {{url>https://..../files_candidats.php 800px}}
